env:
  TERM: alacritty

window:
  padding:
    x: 10
    y: 10
  dynamic_padding: false
  decorations: Full
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true

  class:
    instance: Alacritty
    general: Alacritty

  gtk_theme_variant: None
  opacity: 1

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Hack Nerd Font Mono
    style: Regular
  bold:
    family: Hack Nerd Font Mono
    style: Bold
  italic:
    family: Hack Nerd Font Mono
    style: Italic

  bold_italic:
    family: Hack Nerd Font Mono
    style: Bold Italic
  size: 11.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#212121'
    foreground: '#F2F2F2'
    dim_foreground: '#D9D9D9'
    bright_foreground: '#F2F2F2'

  cursor:
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  normal:
    black:   '#1d1f21'
    red:     '#cc6666'
    green:   '#7dbf2f'
    yellow:  '#f0c674'
    blue:    '#01BABF'
    magenta: '#b294bb'
    cyan:    '#8abeb7'
    white:   '#c5c8c6'

bell:
  animation: EaseOutExpo
  duration: 0
  color: '#ffffff'
  command: None

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: Never
  vi_mode_style: Block
  blink_interval: 0
  unfocused_hollow: true
  thickness: 0.15

live_config_reload: true

shell:
  program: /bin/bash
  args:
    - --login

working_directory: None

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true
